# 1. Import Data & Preview

In [31]:
import numpy as np
import pandas as pd
pd.set_option('display.max_column', None)

import warnings
warnings.filterwarnings('ignore')

In [32]:
demo = pd.read_excel('../Datasets/Raw/Telco_customer_churn_demographics.xlsx')
loc = pd.read_excel('../Datasets/Raw/Telco_customer_churn_location.xlsx')
pop = pd.read_excel('../Datasets/Raw/Telco_customer_churn_population.xlsx')
serv = pd.read_excel('../Datasets/Raw/Telco_customer_churn_services.xlsx')
stat = pd.read_excel('../Datasets/Raw/Telco_customer_churn_status.xlsx')

dataframes = [demo, loc, pop, serv, stat]

In [33]:
for dataframe in dataframes:
    display(dataframe.head())

,Customer ID,Count,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents
0,8779-QRDMV,1,Male,78,No,Yes,No,No,0
1,7495-OOKFY,1,Female,74,No,Yes,Yes,Yes,1
2,1658-BYGOY,1,Male,71,No,Yes,No,Yes,3
3,4598-XLKNJ,1,Female,78,No,Yes,Yes,Yes,1
4,4846-WHAFZ,1,Female,80,No,Yes,Yes,Yes,1

,Customer ID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude
0,8779-QRDMV,1,United States,California,Los Angeles,90022,"34.02381, -118.156582",34.023810,-118.156582
1,7495-OOKFY,1,United States,California,Los Angeles,90063,"34.044271, -118.185237",34.044271,-118.185237
2,1658-BYGOY,1,United States,California,Los Angeles,90065,"34.108833, -118.229715",34.108833,-118.229715
3,4598-XLKNJ,1,United States,California,Inglewood,90303,"33.936291, -118.332639",33.936291,-118.332639
4,4846-WHAFZ,1,United States,California,Whittier,90602,"33.972119, -118.020188",33.972119,-118.020188

   ID  Zip Code  Population
0   1     90001       54492
1   2     90002       44586
2   3     90003       58198
3   4     90004       67852
4   5     90005       43019

,Customer ID,Count,Quarter,Referred a Friend,Number of Referrals,Tenure in Months,Offer,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Internet Type,Avg Monthly GB Download,Online Security,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
0,8779-QRDMV,1,Q3,No,0,1,NaN,No,0.00,No,Yes,DSL,8,No,No,Yes,No,No,Yes,No,No,Month-to-Month,Yes,Bank Withdrawal,39.65,39.65,0.00,20,0.00,59.65
1,7495-OOKFY,1,Q3,Yes,1,8,Offer E,Yes,48.85,Yes,Yes,Fiber Optic,17,No,Yes,No,No,No,No,No,Yes,Month-to-Month,Yes,Credit Card,80.65,633.30,0.00,0,390.80,1024.10
2,1658-BYGOY,1,Q3,No,0,18,Offer D,Yes,11.33,Yes,Yes,Fiber Optic,52,No,No,No,No,Yes,Yes,Yes,Yes,Month-to-Month,Yes,Bank Withdrawal,95.45,1752.55,45.61,0,203.94,1910.88
3,4598-XLKNJ,1,Q3,Yes,1,25,Offer C,Yes,19.76,No,Yes,Fiber Optic,12,No,Yes,Yes,No,Yes,Yes,No,Yes,Month-to-Month,Yes,Bank Withdrawal,98.50,2514.50,13.43,0,494.00,2995.07
4,4846-WHAFZ,1,Q3,Yes,1,37,Offer C,Yes,6.33,Yes,Yes,Fiber Optic,14,No,No,No,No,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36

,Customer ID,Count,Quarter,Satisfaction Score,Customer Status,Churn Label,Churn Value,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,1,Q3,3,Churned,Yes,1,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,1,Q3,3,Churned,Yes,1,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,1,Q3,2,Churned,Yes,1,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,1,Q3,2,Churned,Yes,1,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,1,Q3,2,Churned,Yes,1,67,2793,Price,Extra data charges

# 2. Merge Data

In [34]:
demo = demo.drop(['Count', 'Dependents'], axis=1)
loc = loc.drop(['Count', 'Lat Long'], axis=1)
pop = pop.drop(['ID'], axis=1)
serv = serv.drop(['Count', 'Quarter', 'Referred a Friend', 'Offer'], axis=1)
stat = stat.loc[:, ['Customer ID', 'Churn Label']]

In [35]:
df_master = demo.merge(loc, on='Customer ID', how='inner')
df_master = df_master.merge(serv, on='Customer ID', how='inner')
df_master = df_master.merge(stat, on='Customer ID', how='inner')
df_master = df_master.merge(pop, on='Zip Code', how='inner')

In [36]:
df_master.head()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Number of Dependents,Country,State,City,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Internet Type,Avg Monthly GB Download,Online Security,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Churn Label,Population
0,8779-QRDMV,Male,78,No,Yes,No,0,United States,California,Los Angeles,90022,34.023810,-118.156582,0,1,No,0.00,No,Yes,DSL,8,No,No,Yes,No,No,Yes,No,No,Month-to-Month,Yes,Bank Withdrawal,39.65,39.65,0.00,20,0.00,59.65,Yes,68701
1,7495-OOKFY,Female,74,No,Yes,Yes,1,United States,California,Los Angeles,90063,34.044271,-118.185237,1,8,Yes,48.85,Yes,Yes,Fiber Optic,17,No,Yes,No,No,No,No,No,Yes,Month-to-Month,Yes,Credit Card,80.65,633.30,0.00,0,390.80,1024.10,Yes,55668
2,1658-BYGOY,Male,71,No,Yes,No,3,United States,California,Los Angeles,90065,34.108833,-118.229715,0,18,Yes,11.33,Yes,Yes,Fiber Optic,52,No,No,No,No,Yes,Yes,Yes,Yes,Month-to-Month,Yes,Bank Withdrawal,95.45,1752.55,45.61,0,203.94,1910.88,Yes,47534
3,4598-XLKNJ,Female,78,No,Yes,Yes,1,United States,California,Inglewood,90303,33.936291,-118.332639,1,25,Yes,19.76,No,Yes,Fiber Optic,12,No,Yes,Yes,No,Yes,Yes,No,Yes,Month-to-Month,Yes,Bank Withdrawal,98.50,2514.50,13.43,0,494.00,2995.07,Yes,27778
4,4846-WHAFZ,Female,80,No,Yes,Yes,1,United States,California,Whittier,90602,33.972119,-118.020188,1,37,Yes,6.33,Yes,Yes,Fiber Optic,14,No,No,No,No,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36,Yes,26265

In [37]:
df_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   str
 1   Gender                             7043 non-null   str
 2   Age                                7043 non-null   int64
 3   Under 30                           7043 non-null   str
 4   Senior Citizen                     7043 non-null   str
 5   Married                            7043 non-null   str
 6   Number of Dependents               7043 non-null   int64
 7   Country                            7043 non-null   str
 8   State                              7043 non-null   str
 9   City                               7043 non-null   str
 10  Zip Code                           7043 non-null   int64
 11  Latitude                           7043 non-null   float64
 12  Longitude                          7043 non-null   float64
 13  Number of Referrals                7043 non-null   int64
 14  Tenure in Months                   7043 non-null   int64
 15  Phone Service                      7043 non-null   str
 16  Avg Monthly Long Distance Charges  7043 non-null   float64
 17  Multiple Lines                     7043 non-null   str
 18  Internet Service                   7043 non-null   str
 19  Internet Type                      5517 non-null   str
 20  Avg Monthly GB Download            7043 non-null   int64
 21  Online Security                    7043 non-null   str
 22  Online Backup                      7043 non-null   str
 23  Device Protection Plan             7043 non-null   str
 24  Premium Tech Support               7043 non-null   str
 25  Streaming TV                       7043 non-null   str
 26  Streaming Movies                   7043 non-null   str
 27  Streaming Music                    7043 non-null   str
 28  Unlimited Data                     7043 non-null   str
 29  Contract                           7043 non-null   str
 30  Paperless Billing                  7043 non-null   str
 31  Payment Method                     7043 non-null   str
 32  Monthly Charge                     7043 non-null   float64
 33  Total Charges                      7043 non-null   float64
 34  Total Refunds                      7043 non-null   float64
 35  Total Extra Data Charges           7043 non-null   int64
 36  Total Long Distance Charges        7043 non-null   float64
 37  Total Revenue                      7043 non-null   float64
 38  Churn Label                        7043 non-null   str
 39  Population                         7043 non-null   int64
dtypes: float64(8), int64(8), str(24)
memory usage: 2.1 MB

# 3. Export Data

In [39]:
df_master.to_csv('../Datasets/Raw/Telco_customer_churn_merged.csv', index=False)